### ISSUE TITLE
POST 404 error when uploading or editing an episode with themoviedb and postgres

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [DerVerruckteFuchs/streama#1]
After fetching TV show info from themoviedb, uploading an episode fails at 100% with the error message `File upload failed. Please close this popup and try again.` After editing episode info from themoviedb, when saving, the message `An error occurred.` is shown. It seems whenever info about an episode is committed to the postgres database, it fails. Movies do not have this issue. In `/var/log/apache2/streama-access.log` I see a POST 404 error when I upload. There isn't anything in `/var/log/apache2/streama-error.log`. This occurs with 1.6.0-RC6, but has occurred with previous versions for awhile. I think 1.2.3_beta did not have this issue, but I'll need to test it again.

Workaround:

1. Manually creating an episode and saving works. 

2. Uploading an episode image after creating the manually created episode works.

3. Uploading a video file works. 

Main postgresql log:

```
2018-06-04 06:03:28.891 EDT [5284] streama@streama_db LOG:  execute S_5: select episode0_.id as id1_17_0_, episode0_.version as version2_17_0_, episode0_.api_id as api_id3_17_0_, episode0_.date_created as date_cre4_17_0_, episode0_.deleted as deleted5_17_0_, episode0_.imdb_id as imdb_id6_17_0_, episode0_.intro_end as intro_en7_17_0_, episode0_.intro_start as intro_st8_17_0_, episode0_.last_updated as last_upd9_17_0_, episode0_.original_language as origina10_17_0_, episode0_.outro_start as outro_s11_17_0_, episode0_.overview as overvie12_17_0_, episode0_.popularity as popular13_17_0_, episode0_.report_count as report_14_17_0_, episode0_.vote_average as vote_av15_17_0_, episode0_.vote_count as vote_co16_17_0_, episode0_.air_date as air_dat18_17_0_, episode0_.episode_string as episode19_17_0_, episode0_.episode_number as episode20_17_0_, episode0_.name as name21_17_0_, episode0_.season_number as season_22_17_0_, episode0_.show_id as show_id23_17_0_, episode0_.still_image_id as still_i24_17_0_, episode0_.still_path as still_p25_17_0_ from video episode0_ where episode0_.id=$1 and episode0_.class='streama.Episode'
2018-06-04 06:03:28.891 EDT [5284] streama@streama_db DETAIL:  parameters: $1 = '274'
2018-06-04 06:03:28.891 EDT [5284] streama@streama_db LOG:  execute S_1: COMMIT
```

**Comment by DerVerruckteFuchs** [comment]
Deleting an episode gives a 404 error as well.

**Comment by DerVerruckteFuchs** [comment]
Choosing a local file for an episode gives a GET 500 error along with two messages: `An internal server error occurred.` and `Internal server error`.

streama.war output:

```
Jun 04 06:21:39  streama.war: ERROR org.grails.web.errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [GET] /video/addLocalFile.json
Jun 04 06:21:39  streama.war: Cannot invoke method addToFiles() on null object. Stacktrace follows:
Jun 04 06:21:39  streama.war: java.lang.NullPointerException: Cannot invoke method addToFiles() on null object
Jun 04 06:21:39  streama.war:         at streama.VideoService.$tt__addLocalFile(VideoService.groovy:79)
Jun 04 06:21:39  streama.war:         at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
Jun 04 06:21:39  streama.war:         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
Jun 04 06:21:39  streama.war:         at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
Jun 04 06:21:39  streama.war:         at streama.VideoController.$tt__addLocalFile(VideoController.groovy:208)
Jun 04 06:21:39  streama.war:         at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
Jun 04 06:21:39  streama.war:         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
Jun 04 06:21:39  streama.war:         at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
Jun 04 06:21:39  streama.war:         at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
Jun 04 06:21:39  streama.war:         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
Jun 04 06:21:39  streama.war:         at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
Jun 04 06:21:39  streama.war:         at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:222)
Jun 04 06:21:39  streama.war:         at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
Jun 04 06:21:39  streama.war:         at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
Jun 04 06:21:39  streama.war:         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
Jun 04 06:21:39  streama.war:         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
Jun 04 06:21:39  streama.war:         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
Jun 04 06:21:39  streama.war:         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
Jun 04 06:21:39  streama.war:         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
Jun 04 06:21:39  streama.war:         at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.jav
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilt
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthentic
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwar
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthentication
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:62)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.ja
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
Jun 04 06:21:39  streama.war:         at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
Jun 04 06:21:39  streama.war:         at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
Jun 04 06:21:39  streama.war:         at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
Jun 04 06:21:39  streama.war:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Jun 04 06:21:39  streama.war:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Jun 04 06:21:39  streama.war:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by DerVerruckteFuchs** [comment]
application.yml:
```
# Place this file next to the streama-[version].war on deployment
 environments:
     production:
             dataSource:
                     # potential postgres config
                     dbCreate: update
                     url: jdbc:postgresql://127.0.0.1:5432/streama_db
                     pooled: true
                     jmxExport: true
                     driverClassName: org.postgresql.Driver
                     dialect: org.hibernate.dialect.PostgreSQLDialect
                     username: streama
                     password: <insert_password>
```

**Comment by DerVerruckteFuchs** [comment]
Apache virtual host:
```
<VirtualHost *:443>
SSLEngine on
SSLCertificateFile    /etc/letsencrypt/live/mywebsite.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mywebsite.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH
SSLProtocol All -SSLv2 -SSLv3 -TLSv1 +TLSv1.1
SSLHonorCipherOrder On
Header always set Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
Header always set X-Frame-Options SAMEORIGIN
Header always set X-Content-Type-Options nosniff
Header always set X-XSS-Protection "1; mode=block"

RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK|CUSTOM)
RewriteRule .* - [F]

Header unset Server

ServerSignature Off

ServerName streama.mywebsite.com
ErrorLog ${APACHE_LOG_DIR}/streama-error.log
CustomLog ${APACHE_LOG_DIR}/streama-access.log combined

DocumentRoot "/mnt/streama" 

<Directory /mnt/streama>
    Options All
    AllowOverride All
    Order allow,deny
    allow from all
    Require all granted
</Directory>
    
<Proxy *>
        Order deny,allow
        Allow from all
</Proxy>

  ProxyRequests Off
  ProxyPreserveHost On
  SSLProxyEngine on
  SSLProxyVerify none
  SSLProxyCheckPeerCN off
  SSLProxyCheckPerrName off
  ProxyPass "/" "http://localhost:8080/" timeout=600 Keepalive=On
  ProxyPassReverse "/" "http://localhost:8080/"
  SetEnv proxy-sendchunks 1
  LimitRequestBody 10737420000

SSLUseStapling on
</VirtualHost>
<IfModule mod_ssl.c>
SSLStaplingCache shmcb:/var/run/apache2/stapling_cache(128000)
</IfModule>

**Comment by DerVerruckteFuchs** [comment]
For clarification: saving a show, deleting a show, saving a season, and deleting a season all work just fine. Editing and saving, deleting, and uploading videos for individual TV show episodes all fail with a either a POST 404, or DELETE 404 error. I've verified that there isn't anything broken with how streama interacts with a postgresql database, as movies work just fine in all respects. Something seems to prevent the episode info getting saved. I think streama has made some assumptions about saving TV show episodes that work fine with a mysql database, but not a postgresql database similar to the `user` vs. `users` table issue.

**Comment by DerVerruckteFuchs** [comment]
I think I've narrowed it down to the episode image. If I manually create an episode, it saves just fine. Afterwards I can edit it and add an image with no trouble. However, fetching episodes with an image and trying to save them don't work. There aren't many options for adding or removing images for individual episodes, so that makes it a problem for testing it more directly. Also I think the DELETE 404 error is caused by the episode not being saved, and thus non-existent in the database to be deleted to begin with.

**Comment by DerVerruckteFuchs** [comment]
I checked by adding a show that didn't have any episode images in moviedb, and I still managed to have the problem. So it's back to fetched episodes not saving properly.

**Comment by DerVerruckteFuchs** [comment]
I found a temporary workaround. Manually episodes by episode and season number (name doesn't matter), then using the re-fetch option works.
